### ISSUE TITLE
Additional options for gestalt-cli mutation cmd

### ISSUE THREAD

**Issue by slightlytyler** [charlieschwabacher/gestalt#11]
- [x] user should be able to specify url of the database and skip the prompt
- [x] user should be able to choose the directory of the mutations
- [x] user should be able to glob mutations

___

@charlieschwabacher I'm gonna PR for these later today after I get the dev environment up, let me know if these changes sound reasonable

**Comment by charlieschwabacher** [comment]
Hey Tyler - do you mean the SQL files that `gestalt migrate` will create?

**Comment by slightlytyler** [comment]
I'm adding options to the migrate command @charlieschwabacher. Hooked up `url` and added `directory`, `glob`. These new options allow the user to more easily specify the location of mutations files
