### ISSUE TITLE
400 error when trying to access from client

### ISSUE THREAD

**Issue by n8stowell82** [charlieschwabacher/gestalt#17]
Hi so first off I have to say that I am fairly new to graphQL.  Your project really helped me wrap my head around it and got me up off the ground.

After building my server, I tried to build my client.  I never could get relay to work, so I switched to Apollo.  Apollo is kinda working, but I always get a 400 error back from the server.  In an attempt to cut Apollo out of the picture I a setup a very simple fetch request to see what would happen.  here is my results:
`{"type":"default","status":400,"ok":false,"headers":{"map":{"access-control-allow-credentials":["true"],"date":["Tue, 07 Mar 2017 23:01:11 GMT"],"content-type":["application/json; charset=utf-8"],"content-length":["282"],"x-powered-by":["Express"],"connection":["keep-alive"]}},"url":"http://localhost:3000/graphql","_bodyInit":{},"_bodyBlob":{}}`

I setup cors on my server to allow whitelist the client address, but now I am just stuck.  Any advice would be greatly appreciated!

EDIT:

here is my Apollo client:
`const client = new ApolloClient({
  networkInterface: createNetworkInterface({ uri: '/graphql', credentials: 'include', }),
})`

and here is my fetch request: 
`fetch('http://localhost:3000/graphql')`

maybe I need to add some headers to my fetch request?  but then what is causing my Apollo client to fail?

**Comment by charlieschwabacher** [comment]
Hey - thanks for trying out Gestalt, and great that it helped you get a GraphQL server going!

To make a request directly w/ fetch, you are going to want to use http POST (it uses GET by default), and then you will need to send a GraphQL query in the request body.

Something like this should work:
```javascript
// fetch w/ method POST and content type headers
fetch('http://localhost:3000/graphql', {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  // graphql query in the request body
  body: JSON.stringify({
    query: 'query Q { session { id } }',
  }),
})
  .then(r => r.json()) // parse result as json
  .then(r => { console.log(r); }); // log the result
```

**Comment by n8stowell82** [comment]
You sir are amazing!  Thank you for taking the time to help me out.  That did indeed work and now I can get that sweet data out of my GraphQL server!  Now that I know my server is indeed working correctly, I need to figure out how to get Apollo to work properly.  If you have any insight into Apollo I would love to hear it, but if not, this gets me at least pointed in the right direction.  Thanks again for your help!

**Comment by charlieschwabacher** [comment]
@n8stowell82 no problem - the code creating your Apollo client looks ok to me, can post the full request / response its making to `/graphql` from the network tab of dev tools?

**Comment by n8stowell82** [comment]
@charlieschwabacher thanks again for your willingness to respond and help.  Turns out the problem had to do with me not structuring my query properly.  I "borrowed" the one from your example above and it all started working.  Thanks again for your help!
