### ISSUE TITLE
gestalt init errors with no such file or directory

### ISSUE THREAD

**Issue by proehlen** [charlieschwabacher/gestalt#21]
I've installed `gestalt-cli` globally with `sudo npm install --global gestalt-cli`.    I then ran `gestalt init blogs`.  After the packages are installed, it fails here:
```
Copying files...
gestalt init failed with the error: { Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/gestalt-cli/template/objects/Session.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/node_modules/gestalt-cli/template/objects/Session.js' }
(node:25464) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/gestalt-cli/template/objects/Session.js'
(node:25464) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I notice that I don't have the file that it is complaining about but I do have the same file with a lowercase `s`, ie.: `/usr/lib/node_modules/gestalt-cli/template/objects/session.js` does exist.

**Comment by proehlen** [comment]
A quick investigation reveals this might be the problem:

Line 96 in [/packages/gestalt-cli/src/init.js](https://github.com/charlieschwabacher/gestalt/blob/master/packages/gestalt-cli/src/init.js) says `'objects/Session.js',` 

However this file is named with a capital 'S': 
  [/packages/gestalt-cli/template/objects/session.js](https://github.com/charlieschwabacher/gestalt/blob/master/packages/gestalt-cli/template/objects/session.js).

Just seems bizarre to me that I should be the first person to have this problem since neither file has changed in months.

**Comment by charlieschwabacher** [comment]
Peter - thanks again for catching this!
