### ISSUE TITLE
Mutations in the Example Not Working

### ISSUE THREAD

**Issue by JKing-B16** [charlieschwabacher/gestalt#24]
I was trying to get the example to work, but I keep getting this error:

```
gestalt/blogs/mutations/CreatePost.js:19
      title: types.String,
             ^
ReferenceError: types is not defined
```
It appears that each Mutation example has something like this:
```
inputFields: {
    title: types.String,
    text: types.String,
  },
  outputFields: {
    user: types.User,
  }
```
but the "types" is undefined and this causes babel to croak if you include any of the mutations.

I thought that most likely something needed to be imported, but I was unable to figure out the appropriate source for "types"

**Comment by JKing-B16** [comment]
I found the issue:

in function transformSimpleMutationDefinition(definition) in gestalt-graphql/generate

```
+  Object.keys(definition.inputFields).forEach(function (key) {
-  Object.values(definition.inputFields).forEach(function (key) {
...
+  Object.keys(definition.outputFields).forEach(function (key) {
-  Object.values(definition.outputFields).forEach(function (key) {


```

**Comment by charlieschwabacher** [comment]
updated in 0.0.20 - thank you for catching this!
