### ISSUE TITLE
syntax in Objects/Mutations/Schema for description field

### ISSUE THREAD

**Issue by jacobhausler** [charlieschwabacher/gestalt#4]
Is there currently a syntax for populating the "description" field for each type, field, connection, mutation, etc. in the resulting graphQL schema?

**Comment by charlieschwabacher** [comment]
Hi Jacob - other than mutations (which are defined in javascript), not yet.  I definitely do want a syntax to define both descriptions and deprecation reasons, but haven't wanted to deviate from the spec.  I have been waiting on https://github.com/facebook/graphql/pull/90.

I did experiment with using directives, but it felt unreadable enough not to be worth it to me:
```
type User {
  name: String @metadata(description: "The name of this user")
  posts: Post @relationship(path: "=AUTHORED=>") @metadata(description: "Posts written by this user") 
}
```
Maybe it does make sense to at least have directives in the meantime.. what do you think?  Is the lack of support for descriptions holding you back from using the library?

**Comment by jacobhausler** [comment]
Having no descriptions isn't keeping me back, but it does slow down communicating the schema to my team members. The self-documenting nature of graphQL is one of the big draws for us, so this is high on my list (even if . Once I'm through our weekend hackathon (using Gestalt as our back-end), I'll have more opinions and suggestions. 

- by the way, this package is already pretty great, and has amazing promise.

**Comment by charlieschwabacher** [comment]
Jacob - thanks! and awesome, I asked Lee Byron in that issue thread about the planned syntax for descriptions, and it sounds like it will be javadoc style comments.  I don't think I will add anything to gestalt until that lands in graphql-js, but I'm pretty excited about that syntax 🎉 .

I'll be around today, so if you run into any trouble w/ Gestalt or have other questions during the hackathon, feel free to chat me on reactiflux (`@charlie`).  Or, just open issues here and I'll try to respond quickly.

**Comment by charlieschwabacher** [comment]
Made a pull into graphql-js adding a comment syntax for type system description definition: https://github.com/graphql/graphql-js/pull/427

**Comment by jacobhausler** [comment]
This would make the schema so much less cluttered than the @metadata directive!
