### ISSUE TITLE
async update(table, object, escapes) function in /gestalt-postgres/src/DB.js

### ISSUE THREAD

**Issue by jacobhausler** [charlieschwabacher/gestalt#5]
proposed compliment to async insert(table, object) would execute UPDATE SET WHERE queries

```
// updates the db based on a table name, constraints, and column:value key pair in object
  async update(
    table: string,
    object: Object,
    conditions: Object,
  ): Promise<Object> {

    ...

    const result = await this.exec(
      `UPDATE ... SET ... WHERE ... RETURNING *;`, 
    );

    ...

    return [altered row];
  }

```

example:

updating a "hosts_by_location_id" column for updating a User's default Location (Location=HOSTS=>User, User <-HOSTS- Location)

**Comment by charlieschwabacher** [comment]
Love it 👍 - if you want to put together a pull, I'll merge it.  Otherwise, I'll add this in the next few days.

**Comment by charlieschwabacher** [comment]
added this
