### ISSUE TITLE
Getting a 404 for OPTIONS request to gestalt server

### ISSUE THREAD

**Issue by slightlytyler** [charlieschwabacher/gestalt#6]
I'm using apollo client on the front end. The server works fine with graphiql due to it omitting the OPTIONS request and just POSTing

**Comment by charlieschwabacher** [comment]
Hi Tyler - if you are making cross domain requests (even different ports count), you will need to add some kind of CORS middleware to express.  This is a good one: https://www.npmjs.com/package/cors.

If you add that in `server.js` before the `app.use(gestaltServer...` line, I think it will fix your problem.

**Comment by slightlytyler** [comment]
Knew we were missing something!
