### ISSUE TITLE
Session type in blog-example doesn't work outside of GraphiQL

### ISSUE THREAD

**Issue by jacobhausler** [charlieschwabacher/gestalt#7]
The method of resolving the currentUser field of the Session type in the blog-example works for a session in graphiQL (caveat, se below), but when connected outside of graphQL (via Apollo client, for example), queries and mutations return session objects with null currentUser fields. 

Inside of graphiQL, Session tracks currentUser correctly, but always returns "Session:null" for the id field of Session. 

Any ideas? Our repo is here: https://github.com/jacobhausler/gestaltCLP2

**Comment by jacobhausler** [comment]
I see that gestalt-server is using cookie-session, but i'm not clear if gestalt-server is generating, storing, timing out sessions, killing sessions, etc

**Comment by jacobhausler** [comment]
It looks like the session middleware is feeding the graphqlHTTP the session that comes in from req; what happens if {session} = request is undefined? I don't think that new sessions or session IDs are being generated

**Comment by charlieschwabacher** [comment]
Hey - I don't know much about apollo, but w/ relay you need to configure the network layer to allow cookies on cross domain requests.  You can see an example in the blogs example here:

https://github.com/charlieschwabacher/gestalt/blob/master/packages/blogs-example/client/index.js#L10

If apollo is using fetch I think it would need the same kind of configuration.

**Comment by charlieschwabacher** [comment]
I found the apollo docs I was looking for (http://docs.apollostack.com/apollo-client/index.html#createNetworkInterface) - It looks like you can do something like this:

```javascript
const networkInterface = createNetworkInterface(
  'https://example.com/graphql',
  {credentials: 'include'}
);
```

**Comment by jacobhausler** [comment]
cookie-sessions has an httpOnly method that disables CORS by default. we solved enabling CORS using the cors package, but I think that cookie-sessions needs httpOnly disabled as well. i'll test on both ends

**Comment by charlieschwabacher** [comment]
Hey - if you weren't already able to get it to work, I made a cross origin version of the blogs example here: https://gist.github.com/charlieschwabacher/991a6892205df1802459ee6d742d950a

I had to add some extra configuration to the cors middleware, the `credentials: true` option on cors tells the server to accept cross origin cookies, and then the `credentials: 'include'` on the client tells fetch to send them.

I also had to specify the domain directly in the cors configuration (`origin: 'http://localhost:3000'`), although I'm not sure why the default `*` would not work there.
