### ISSUE TITLE
node RootQuery is making incorrect SQL calls

### ISSUE THREAD

**Issue by jacobhausler** [charlieschwabacher/gestalt#8]
Hey,

The following query returns a syntax error (the record exists in my db):
```
query{
  node(id:"0409c1bd-6652-4e31-9f92-24bdf07968ba"){
	... on User{
            id
            fullName
    }
  }
}
```
This is the query that is being run by the Database Adapter:
```
SELECT * FROM 0409c1bd_6652_4e31_9f92_24bdf07968bas WHERE id = $1; [null]
```

Can you advise how type resolution works with the Node query, and why the query is calling the id as the table name instead of as $1?

**Comment by charlieschwabacher** [comment]
Hey - the node ids are equal to ``${typeName}:${databaseId}``, so to get the type and database id it just splits on the colon.  This should work:

```graphql
query{
  node(id:"User:0409c1bd-6652-4e31-9f92-24bdf07968ba"){
    ... on User{
            id
            fullName
    }
  }
}
```

But this should definitely raise a more descriptive error when the id isn't valid.. going to leave this issue open to track adding that check.

**Comment by charlieschwabacher** [comment]
added a descriptive error message here
